/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as DocsIndexRouteImport } from './routes/_docs/index'
import { Route as DocsInstallationRouteImport } from './routes/_docs/installation'
import { Route as DocsComponentsLoadingRouteImport } from './routes/_docs/components/loading'
import { Route as DocsComponentsLoadingStackedRouteImport } from './routes/_docs/components/loading-stacked'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsLoadingRoute = DocsComponentsLoadingRouteImport.update({
  id: '/components/loading',
  path: '/components/loading',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsLoadingStackedRoute =
  DocsComponentsLoadingStackedRouteImport.update({
    id: '/components/loading-stacked',
    path: '/components/loading-stacked',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DocsIndexRoute
  '/installation': typeof DocsInstallationRoute
  '/components/loading': typeof DocsComponentsLoadingRoute
  '/components/loading-stacked': typeof DocsComponentsLoadingStackedRoute
}
export interface FileRoutesByTo {
  '/installation': typeof DocsInstallationRoute
  '/': typeof DocsIndexRoute
  '/components/loading': typeof DocsComponentsLoadingRoute
  '/components/loading-stacked': typeof DocsComponentsLoadingStackedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/installation': typeof DocsInstallationRoute
  '/_docs/': typeof DocsIndexRoute
  '/_docs/components/loading': typeof DocsComponentsLoadingRoute
  '/_docs/components/loading-stacked': typeof DocsComponentsLoadingStackedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/installation'
    | '/components/loading'
    | '/components/loading-stacked'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/installation'
    | '/'
    | '/components/loading'
    | '/components/loading-stacked'
  id:
    | '__root__'
    | '/_docs'
    | '/_docs/installation'
    | '/_docs/'
    | '/_docs/components/loading'
    | '/_docs/components/loading-stacked'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/': {
      id: '/_docs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/installation': {
      id: '/_docs/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/components/loading': {
      id: '/_docs/components/loading'
      path: '/components/loading'
      fullPath: '/components/loading'
      preLoaderRoute: typeof DocsComponentsLoadingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/components/loading-stacked': {
      id: '/_docs/components/loading-stacked'
      path: '/components/loading-stacked'
      fullPath: '/components/loading-stacked'
      preLoaderRoute: typeof DocsComponentsLoadingStackedRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsLoadingRoute: typeof DocsComponentsLoadingRoute
  DocsComponentsLoadingStackedRoute: typeof DocsComponentsLoadingStackedRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsInstallationRoute: DocsInstallationRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsLoadingRoute: DocsComponentsLoadingRoute,
  DocsComponentsLoadingStackedRoute: DocsComponentsLoadingStackedRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
